# Generated by Django 2.2 on 2023-03-27 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_post_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postname',
            new_name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='작성일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='dt_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
    ]
