# Generated by Django 2.2 on 2023-04-01 14:48

import board.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20230327_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, '너무 짧습니다. 10자 이상 적어주세요.'), board.validators.validate_symbols]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(error_messages={'unique': '중복된 제목은 등록할 수 없습니다!'}, max_length=50, unique=True),
        ),
    ]
